# Generated by Django 3.2.6 on 2021-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonatorAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donator',
            name='mail',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donator',
            name='number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
