# Generated by Django 3.2.6 on 2021-08-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
