# Generated by Django 3.2.6 on 2021-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.DecimalField(decimal_places=5, max_digits=5)),
                ('name', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
