# Generated by Django 3.2.6 on 2021-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPP', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Voluntario')]),
        ),
    ]
