# Generated by Django 3.2.6 on 2021-08-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DonatorAPP', '0001_initial'),
        ('UserAPP', '0002_alter_user_rol'),
        ('CampaignAPP', '0002_alter_campaign_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageAddress', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Received'), (3, 'Assigned'), (4, 'Delivered'), (5, 'Expired')])),
                ('campaignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampaignAPP.campaign')),
                ('donatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonatorAPP.donator')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAPP.user')),
            ],
        ),
    ]
