# Generated by Django 3.2.6 on 2021-11-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donatorId',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='userId',
        ),
    ]
