# Generated by Django 3.2.6 on 2021-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationAPP', '0002_auto_20211104_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignada'), (3, 'Recibida'), (4, 'Entregada'), (5, 'Vencida')]),
        ),
    ]
