# Generated by Django 3.2.6 on 2021-11-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DonationAPP', '0001_initial'),
        ('DonatedElementAPP', '0003_donatedelement_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedelement',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonationAPP.donation'),
        ),
    ]
