# Generated by Django 3.2.6 on 2021-11-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DonationAPP', '0003_alter_donation_status'),
        ('DonatedElementAPP', '0004_alter_donatedelement_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedelement',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatedElements', to='DonationAPP.donation'),
        ),
    ]
